name: Refresh GitHub Readme Stats Cache

on:
  schedule:
    - cron: "0 */12 * * *"   # Atualiza a cada 12 horas
  workflow_dispatch:          # Permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Hit GitHub Readme Stats API to refresh cache
        run: |
          curl -s "https://github-readme-stats.vercel.app/api?username=gabrielbribeiroo&count_private=true&show_icons=true" > /dev/null

    env:
      PAT_1: ${{ secrets.PAT_1 }}
